# This file was generated by GoReleaser. DO NOT EDIT.
class Flog < Formula
  desc "A fake log generator for common log formats"
  homepage "https://github.com/mingrammer/flog"
  url "https://github.com/mingrammer/flog/releases/download/v0.3.0/flog_0.3.0_darwin_amd64.tar.gz"
  version "0.3.0"
  sha256 "418c78c4ae003863d60f4303e68a543e467d4af19589d6d6eba64898d6406c8f"

  def install
    bin.install "flog"
  end
end
