# This file was generated by GoReleaser. DO NOT EDIT.
class Flog < Formula
  desc "A fake log generator for common log formats"
  homepage "https://github.com/mingrammer/flog"
  url "https://github.com/mingrammer/flog/releases/download/v0.3.2/flog_0.3.2_darwin_amd64.tar.gz"
  version "0.3.2"
  sha256 "645dbaf14777f018e184cf1348dcf313d115ee360f2c1ff1e33d07b8dda2b2b9"

  def install
    bin.install "flog"
  end
end
